### ISSUE TITLE
Probably not anything super important.

### ISSUE THREAD

**Issue by EmanYm** [KidsDontPlay/LimeLib#7]
I noticed this in my console...

>[13:24:49] [Server thread/WARN] [FML]: ****************************************
[13:24:49] [Server thread/WARN] [FML]: * Dangerous alternative prefix `unknown` for name `unknown`, expected `limelib` invalid registry invocation/invalid name?
[13:24:49] [Server thread/WARN] [FML]: *  at net.minecraftforge.registries.IForgeRegistryEntry$Impl.setRegistryName(IForgeRegistryEntry.java:85)
[13:24:49] [Server thread/WARN] [FML]: *  at net.minecraftforge.registries.IForgeRegistryEntry$Impl.setRegistryName(IForgeRegistryEntry.java:94)
[13:24:49] [Server thread/WARN] [FML]: *  at mrriegel.limelib.util.Serious.preinit(Serious.java:29)
[13:24:49] [Server thread/WARN] [FML]: *  at mrriegel.limelib.LimeLib.preInit(LimeLib.java:46)
[13:24:49] [Server thread/WARN] [FML]: *  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[13:24:49] [Server thread/WARN] [FML]: *  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)...
[13:24:49] [Server thread/WARN] [FML]: ****************************************

SpongeForge 1.12-beta-2474
Limelib 1.12-1.7.4

**Comment by KidsDontPlay** [comment]
just ignore it.
I fixed it
